name: Node.js publish online @ explorer.photon-ai.com

on:
  release:
    types: [released]

jobs:
  build_and_publish:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: docker build and push
      with:
        addLatest: True
        image: photonai-explorer
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
